# Build the functions code ...
FROM maven:3.6.3-jdk-11 AS builder
COPY src /usr/src/app/src
COPY pom.xml /usr/src/app
RUN mvn -f /usr/src/app/pom.xml clean package -P kafka-producer

# ... and run the web server!
FROM openjdk:8
WORKDIR /
COPY --from=builder /usr/src/app/target/graph-analytics-functions-app*jar-with-dependencies.jar graph-analytics-functions-app.jar
COPY data /data
CMD java -jar graph-analytics-functions-app.jar sx-mathoverflow-test
